# Generated by Django 4.0.6 on 2022-07-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
