# Generated by Django 4.0.6 on 2022-07-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Com',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=125)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
