# Generated by Django 4.0.6 on 2022-07-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_com_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('comment', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Com',
        ),
    ]
