# Generated by Django 4.0.6 on 2022-07-31 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_comment_delete_com'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
