# Generated by Django 4.0.6 on 2022-07-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_remove_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_pig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comment_kenguru',
        ),
    ]
