# Generated by Django 4.0.6 on 2022-07-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_comment_pig_rename_comment_comment_kenguru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_kenguru',
            name='comment',
            field=models.TextField(max_length=255, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='comment_pig',
            name='comment',
            field=models.TextField(max_length=255, verbose_name='Комментарии'),
        ),
    ]
